remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
#theme: jekyll-theme-cayman
title: Combi-Lab
description: [Computational Biology Laboratory - FURG]
show_downloads: false
